# Generated by Django 4.2.4 on 2023-09-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='name',
            field=models.CharField(default='def', max_length=200),
            preserve_default=False,
        ),
    ]
